# Generated by Django 5.1.3 on 2025-09-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0017_rename_consumo_diario_fluxoagua_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='consumodiario',
            name='data',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='consumodiario',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_diarios', to='fluxo.sensor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluxoagua',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='fluxo.sensor'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='consumodiario',
            constraint=models.UniqueConstraint(fields=('sensor', 'data'), name='unique_sensor_data'),
        ),
    ]
