# Generated by Django 5.1.3 on 2025-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0018_sensor_alter_consumodiario_data_consumodiario_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumodiario',
            name='consumo_total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fluxoagua',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
