# Generated by Django 5.1.3 on 2025-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0020_alter_consumodiario_consumo_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoagua',
            name='valor_diferenca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
