# Generated by Django 5.1.3 on 2025-10-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0021_fluxoagua_valor_diferenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('on', 'Ligado'), ('off', 'Desligado')], default='on', max_length=3)),
                ('desligamento_automatico_ocorreu', models.BooleanField(default=False)),
                ('usuario_alterou_manualmente', models.BooleanField(default=False)),
                ('data_hora_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Controle de Fluxo',
                'verbose_name_plural': 'Controles de Fluxo',
            },
        ),
        migrations.CreateModel(
            name='MetaConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_diaria_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta de Consumo',
                'verbose_name_plural': 'Metas de Consumo',
            },
        ),
    ]
