# Generated by Django 5.1.3 on 2025-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0022_controlefluxo_metaconsumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email de Notificação',
                'verbose_name_plural': 'Emails de Notificação',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='controlefluxo',
            name='email_enviado_hoje',
            field=models.BooleanField(default=False),
        ),
    ]
